// Disclaimer: this file was generated by AI.
import { appendFileSync, readFileSync, readdirSync, statSync, unlinkSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { createHash } from 'node:crypto'
import { default as tildify } from 'tildify'

export interface LlmStreamResult {
	responseId?: string
	responseModel?: string
	stopReason: string
	assistantContent: string
	reasoningContent: string
	usage: any
}

export interface LlmLogData extends LlmStreamResult {
	model: string
	system: string
	content: string
}

export interface LlmMessage {
	role: 'system' | 'user' | 'assistant'
	content: string
}

export interface LlmSession {
	logFile: string
	parentId: string
	messages: LlmMessage[]
	source: string
}

export function readLlmSession(logDir: string, id: string): LlmSession {
	if (!/^\d+$/.test(id)) throw new Error('Expected a session ID from llm-<id>.jsonl')
	const logFile = join(logDir, `llm-${id}.jsonl`)
	const source = readFileSync(logFile, 'utf8')
	const [header, ...entries] = source.trimEnd().split('\n').map(line => JSON.parse(line))
	const invalid = () => new Error(`Unsupported or damaged LLM session: ${logFile}`)
	if (header?.type != 'session' || header.version != 3 || !entries.length) throw invalid()
	const messages: LlmMessage[] = []
	const ids = new Set<string>()
	let parentId: string | null = null
	for (const entry of entries) {
		const role = messages.length % 2 == 0 ? 'user' : 'assistant'
		if (entry?.type != 'message' || typeof entry.id != 'string' || !entry.id || ids.has(entry.id)
			|| entry.parentId !== parentId || entry.message?.role != role) throw invalid()
		const content = entry.message.content
		let text = ''
		if (role == 'user') {
			if (typeof content != 'string') throw invalid()
			text = content
		} else {
			if (!Array.isArray(content)) throw invalid()
			for (const block of content) {
				if (block?.type == 'text' && typeof block.text == 'string') text += block.text
				else if (block?.type != 'thinking' || typeof block.thinking != 'string') throw invalid()
			}
		}
		messages.push({ role, content: text })
		ids.add(entry.id)
		parentId = entry.id
	}
	if (messages.length % 2 != 0 || parentId == null) throw invalid()
	return { logFile, parentId, messages, source }
}

export async function* collectOpenAIChatStream(
	events: AsyncIterable<{ data: string }>,
	result: LlmStreamResult,
	reasoning = true,
): AsyncGenerator<string> {
	for await (const event of events) {
		if (event.data === '[DONE]') break

		const chunk = JSON.parse(event.data)
		const { id, model, choices, usage, lastOne } = chunk
		const item = Array.isArray(choices) ? choices[0] : undefined
		result.responseId ??= id
		result.responseModel ??= model
		if (usage) {
			result.usage = usage
		}

		if (!item) {
			if (lastOne) break
			continue
		}

		const delta = item.delta ?? {}
		if (delta.reasoning_content) {
			result.reasoningContent += delta.reasoning_content
			if (reasoning) yield delta.reasoning_content
		}

		if (delta.content) {
			result.assistantContent += delta.content
			yield delta.content
		}

		if (item.finish_reason) {
			result.stopReason = normalizeStopReason(item.finish_reason)
		}
		if (lastOne) break
	}
}

export function normalizeLlmUsage(usage: any) {
	const promptTokens = usage?.prompt_tokens ?? usage?.input_tokens ?? usage?.input ?? 0
	const completionTokens = usage?.completion_tokens ?? usage?.output_tokens ?? usage?.output ?? 0
	const totalTokens = usage?.total_tokens ?? usage?.totalTokens ?? usage?.total ?? promptTokens + completionTokens
	return { promptTokens, completionTokens, totalTokens }
}

export function writePiStyleLlmLog(logDir: string, data: LlmLogData, session?: LlmSession): string {
	const now = Date.now()
	const timestamp = new Date(now).toISOString()
	const sessionId = shortHash(`${timestamp}\0${data.content}`)
	const userEntryId = shortHash(`${sessionId}\0${session?.parentId ?? ''}\0user`)
	const assistantEntryId = shortHash(`${userEntryId}\0assistant`)
	const logFile = session?.logFile ?? join(logDir, `llm-${Math.floor(now / 1000)}.jsonl`)
	const { promptTokens, completionTokens, totalTokens } = normalizeLlmUsage(data.usage)
	const assistantContent: any[] = []
	if (data.reasoningContent) {
		assistantContent.push({ type: 'thinking', thinking: data.reasoningContent })
	}
	if (data.assistantContent) {
		assistantContent.push({ type: 'text', text: data.assistantContent })
	}

	const lines = [
		{
			type: 'session',
			version: 3,
			id: sessionId,
			timestamp,
			cwd: process.cwd(),
		},
		{
			type: 'message',
			id: userEntryId,
			parentId: session?.parentId ?? null,
			timestamp,
			message: {
				role: 'user',
				content: !session && data.system ? `System: ${data.system}\n\n${data.content}` : data.content,
				timestamp: now,
			},
		},
		{
			type: 'message',
			id: assistantEntryId,
			parentId: userEntryId,
			timestamp: new Date().toISOString(),
			message: {
				role: 'assistant',
				content: assistantContent,
				api: 'openai-completions',
				provider: 'custom',
				model: data.model,
				responseModel: data.responseModel,
				responseId: data.responseId,
				usage: {
					input: promptTokens,
					output: completionTokens,
					cacheRead: 0,
					cacheWrite: 0,
					totalTokens,
					cost: {
						input: 0,
						output: 0,
						cacheRead: 0,
						cacheWrite: 0,
						total: 0,
					},
				},
				rawUsage: data.usage,
				stopReason: data.stopReason,
				timestamp: Date.now(),
			},
		},
	]
	if (session) {
		if (readFileSync(logFile, 'utf8') != session.source) throw new Error(`Session changed during request: ${logFile}`)
		const prefix = session.source.endsWith('\n') ? '' : '\n'
		appendFileSync(logFile, `${prefix}${lines.slice(1).map(line => JSON.stringify(line)).join('\n')}\n`)
	} else {
		writeFileSync(logFile, `${lines.map(line => JSON.stringify(line)).join('\n')}\n`)
	}
	return tildify(logFile)
}

export function pruneLlmLogs(logDir: string, keep = 5): void {
	const logFiles = readdirSync(logDir).filter(f => f.startsWith('llm-') && f.endsWith('.jsonl'))
	if (logFiles.length > keep) {
		logFiles.map(file => ({ file, mtime: statSync(join(logDir, file)).mtimeMs }))
			.sort((a, b) => a.mtime - b.mtime)
			.slice(0, logFiles.length - keep).forEach(({ file }) => unlinkSync(join(logDir, file)))
	}
}

function normalizeStopReason(finishReason: string): string {
	return finishReason === 'length' ? 'length' : finishReason === 'tool_calls' ? 'toolUse' : 'stop'
}

function shortHash(input: string): string {
	return createHash('sha256').update(input).digest('hex').slice(0, 16)
}
