// Disclaimer: this file was generated by AI.
import { readdirSync, unlinkSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { createHash } from 'node:crypto'
import { default as tildify } from 'tildify'

export interface LlmStreamResult {
	responseId?: string
	responseModel?: string
	stopReason: string
	assistantContent: string
	reasoningContent: string
	usage: any
}

export interface LlmLogData extends LlmStreamResult {
	model: string
	system: string
	content: string
}

export async function* collectOpenAIChatStream(
	events: AsyncIterable<{ data: string }>,
	result: LlmStreamResult,
	reasoning = true,
): AsyncGenerator<string> {
	for await (const event of events) {
		if (event.data === '[DONE]') break

		const chunk = JSON.parse(event.data)
		const { id, model, choices, usage, lastOne } = chunk
		const item = Array.isArray(choices) ? choices[0] : undefined
		result.responseId ??= id
		result.responseModel ??= model
		if (usage) {
			result.usage = usage
		}

		if (!item) {
			if (lastOne) break
			continue
		}

		const delta = item.delta ?? {}
		if (delta.reasoning_content) {
			result.reasoningContent += delta.reasoning_content
			if (reasoning) yield delta.reasoning_content
		}

		if (delta.content) {
			result.assistantContent += delta.content
			yield delta.content
		}

		if (item.finish_reason) {
			result.stopReason = normalizeStopReason(item.finish_reason)
		}
		if (lastOne) break
	}
}

export function normalizeLlmUsage(usage: any) {
	const promptTokens = usage?.prompt_tokens ?? usage?.input_tokens ?? usage?.input ?? 0
	const completionTokens = usage?.completion_tokens ?? usage?.output_tokens ?? usage?.output ?? 0
	const totalTokens = usage?.total_tokens ?? usage?.totalTokens ?? usage?.total ?? promptTokens + completionTokens
	return { promptTokens, completionTokens, totalTokens }
}

export function writePiStyleLlmLog(logDir: string, data: LlmLogData): string {
	const now = Date.now()
	const timestamp = new Date(now).toISOString()
	const sessionId = shortHash(`${timestamp}\0${data.content}`)
	const userEntryId = shortHash(`${sessionId}\0user`)
	const assistantEntryId = shortHash(`${sessionId}\0assistant`)
	const logFile = join(logDir, `llm-${Math.floor(now / 1000)}.jsonl`)
	const { promptTokens, completionTokens, totalTokens } = normalizeLlmUsage(data.usage)
	const assistantContent: any[] = []
	if (data.reasoningContent) {
		assistantContent.push({ type: 'thinking', thinking: data.reasoningContent })
	}
	if (data.assistantContent) {
		assistantContent.push({ type: 'text', text: data.assistantContent })
	}

	const lines = [
		{
			type: 'session',
			version: 3,
			id: sessionId,
			timestamp,
			cwd: process.cwd(),
		},
		{
			type: 'message',
			id: userEntryId,
			parentId: null,
			timestamp,
			message: {
				role: 'user',
				content: data.system ? `System: ${data.system}\n\n${data.content}` : data.content,
				timestamp: now,
			},
		},
		{
			type: 'message',
			id: assistantEntryId,
			parentId: userEntryId,
			timestamp: new Date().toISOString(),
			message: {
				role: 'assistant',
				content: assistantContent,
				api: 'openai-completions',
				provider: 'custom',
				model: data.model,
				responseModel: data.responseModel,
				responseId: data.responseId,
				usage: {
					input: promptTokens,
					output: completionTokens,
					cacheRead: 0,
					cacheWrite: 0,
					totalTokens,
					cost: {
						input: 0,
						output: 0,
						cacheRead: 0,
						cacheWrite: 0,
						total: 0,
					},
				},
				rawUsage: data.usage,
				stopReason: data.stopReason,
				timestamp: Date.now(),
			},
		},
	]
	writeFileSync(logFile, `${lines.map(line => JSON.stringify(line)).join('\n')}\n`)
	return tildify(logFile)
}

export function pruneLlmLogs(logDir: string, keep = 5): void {
	const logFiles = readdirSync(logDir).filter(f => f.startsWith('llm-') && f.endsWith('.jsonl'))
	if (logFiles.length > keep) {
		logFiles.sort().slice(0, logFiles.length - keep).forEach(f => unlinkSync(join(logDir, f)))
	}
}

function normalizeStopReason(finishReason: string): string {
	return finishReason === 'length' ? 'length' : finishReason === 'tool_calls' ? 'toolUse' : 'stop'
}

function shortHash(input: string): string {
	return createHash('sha256').update(input).digest('hex').slice(0, 16)
}
