// Disclaimer: this file was generated by AI.
/**
 * Standalone markdown-to-ANSI renderer.
 * Extracted and adapted from @mariozechner/pi-tui's Markdown component.
 *
 * Uses marked.lexer() to parse markdown into tokens, then renders each token
 * with configurable ANSI styling via a MarkdownTheme.
 */

import { Marked, type Token, Tokenizer, type Tokens } from 'marked'
import { highlight, supportsLanguage, type Theme as CliHighlightTheme } from 'cli-highlight'

// ---------------------------------------------------------------------------
// ANSI / width utilities
// ---------------------------------------------------------------------------

const segmenter = new Intl.Segmenter(undefined, { granularity: 'grapheme' })

/** Strip ANSI escape sequences. Handles CSI, OSC 8, and APC sequences. */
export function extractAnsiCode(str: string, pos: number): { code: string; length: number } | null {
	if (pos >= str.length || str[pos] !== '\x1b') return null
	const next = str[pos + 1]

	// CSI: ESC [ ... letter
	if (next === '[') {
		let j = pos + 2
		while (j < str.length && !/[mGKHJ]/.test(str[j]!)) j++
		if (j < str.length) return { code: str.substring(pos, j + 1), length: j + 1 - pos }
		return null
	}

	// OSC: ESC ] ... BEL or ST (ESC \)
	if (next === ']') {
		let j = pos + 2
		while (j < str.length) {
			if (str[j] === '\x07') return { code: str.substring(pos, j + 1), length: j + 1 - pos }
			if (str[j] === '\x1b' && str[j + 1] === '\\') return { code: str.substring(pos, j + 2), length: j + 2 - pos }
			j++
		}
		return null
	}

	// APC: ESC _ ... BEL or ST
	if (next === '_') {
		let j = pos + 2
		while (j < str.length) {
			if (str[j] === '\x07') return { code: str.substring(pos, j + 1), length: j + 1 - pos }
			if (str[j] === '\x1b' && str[j + 1] === '\\') return { code: str.substring(pos, j + 2), length: j + 2 - pos }
			j++
		}
		return null
	}

	return null
}

// Simple east-asian width for CJK characters.
function isFullwidth(cp: number): boolean {
	return (
		(cp >= 0x1100 && cp <= 0x115f) || // Hangul Jamo
		(cp >= 0x2329 && cp <= 0x232a) || // Angle brackets
		(cp >= 0x2e80 && cp <= 0x303e) || // CJK Radicals, Kangxi, etc.
		(cp >= 0x3040 && cp <= 0x33bf) || // Hiragana, Katakana, Bopomofo, Hangul, CJK compatibility
		(cp >= 0x3400 && cp <= 0x4dbf) || // CJK Unified Extension A
		(cp >= 0x4e00 && cp <= 0xa4cf) || // CJK Unified, Yi
		(cp >= 0xac00 && cp <= 0xd7a3) || // Hangul Syllables
		(cp >= 0xf900 && cp <= 0xfaff) || // CJK Compatibility Ideographs
		(cp >= 0xfe10 && cp <= 0xfe19) || // Vertical forms
		(cp >= 0xfe30 && cp <= 0xfe6f) || // CJK Compatibility Forms
		(cp >= 0xff01 && cp <= 0xff60) || // Fullwidth forms
		(cp >= 0xffe0 && cp <= 0xffe6) || // Fullwidth signs
		(cp >= 0x1f000 && cp <= 0x1fbff) || // Emoji & Pictographs
		(cp >= 0x20000 && cp <= 0x3ffff) // CJK Extension B+ & compatibility supplement
	)
}

const zeroWidthRegex = /^(?:\p{Default_Ignorable_Code_Point}|\p{Control}|\p{Mark}|\p{Surrogate})+$/v
const leadingNonPrintingRegex = /^[\p{Default_Ignorable_Code_Point}\p{Control}\p{Format}\p{Mark}\p{Surrogate}]+/v
const rgiEmojiRegex = /^\p{RGI_Emoji}$/v

function graphemeWidth(segment: string): number {
	if (zeroWidthRegex.test(segment)) return 0

	// Emoji check
	const cp = segment.codePointAt(0)!
	if (
		(cp >= 0x1f000 && cp <= 0x1fbff) ||
		(cp >= 0x2300 && cp <= 0x27bf) ||
		segment.includes('\uFE0F') ||
		segment.length > 2
	) {
		if (rgiEmojiRegex.test(segment)) return 2
	}

	// Regional indicators
	if (cp >= 0x1f1e6 && cp <= 0x1f1ff) return 2

	const base = segment.replace(leadingNonPrintingRegex, '')
	const baseCp = base.codePointAt(0)
	if (baseCp === undefined) return 0

	if (isFullwidth(baseCp)) return 2
	return 1
}

/** Calculate visible terminal width of a string (ANSI codes excluded). */
export function visibleWidth(str: string): number {
	if (str.length === 0) return 0
	let clean = str
	if (clean.includes('\x1b')) {
		let stripped = ''
		let i = 0
		while (i < clean.length) {
			const ansi = extractAnsiCode(clean, i)
			if (ansi) { i += ansi.length; continue }
			stripped += clean[i]
			i++
		}
		clean = stripped
	}
	let width = 0
	for (const { segment } of segmenter.segment(clean)) {
		width += graphemeWidth(segment)
	}
	return width
}

// ---------------------------------------------------------------------------
// ANSI code tracker – preserves active styles across wrapped lines
// ---------------------------------------------------------------------------

class AnsiCodeTracker {
	private bold = false
	private italic = false
	private underline = false
	private strikethrough = false
	private fgColor: string | null = null

	process(ansiCode: string): void {
		if (!ansiCode.endsWith('m')) return
		const match = ansiCode.match(/\x1b\[([\d;]*)m/)
		if (!match) return
		const params = match[1]
		if (params === '' || params === '0') { this.reset(); return }
		const parts = params.split(';')
		let i = 0
		while (i < parts.length) {
			const code = Number.parseInt(parts[i]!, 10)
			if (code === 38 || code === 48) {
				// 256-color / RGB – skip parameters
				const nextMode = parts[i + 1]
				const n = nextMode === '2' ? 5 : 3
				const colorCode = parts.slice(i, i + n).join(';')
				if (code === 38) this.fgColor = colorCode
				i += n
				continue
			}
			switch (code) {
				case 0: this.reset(); break
				case 1: this.bold = true; break
				case 3: this.italic = true; break
				case 4: this.underline = true; break
				case 9: this.strikethrough = true; break
				case 22: this.bold = false; break
				case 23: this.italic = false; break
				case 24: this.underline = false; break
				case 29: this.strikethrough = false; break
				case 39: this.fgColor = null; break
				default:
					if ((code >= 30 && code <= 37) || (code >= 90 && code <= 97)) this.fgColor = String(code)
					break
			}
			i++
		}
	}

	reset(): void {
		this.bold = false
		this.italic = false
		this.underline = false
		this.strikethrough = false
		this.fgColor = null
	}

	getActiveCodes(): string {
		const codes: string[] = []
		if (this.bold) codes.push('1')
		if (this.italic) codes.push('3')
		if (this.underline) codes.push('4')
		if (this.strikethrough) codes.push('9')
		if (this.fgColor) codes.push(this.fgColor)
		return codes.length > 0 ? `\x1b[${codes.join(';')}m` : ''
	}
}

// ---------------------------------------------------------------------------
// ANSI-aware word wrapping
// ---------------------------------------------------------------------------

function splitIntoTokensWithAnsi(text: string): string[] {
	const tokens: string[] = []
	let current = ''
	let pendingAnsi = ''
	let inWhitespace = false
	let i = 0

	while (i < text.length) {
		const ansiResult = extractAnsiCode(text, i)
		if (ansiResult) {
			pendingAnsi += ansiResult.code
			i += ansiResult.length
			continue
		}
		const char = text[i]!
		const charIsSpace = char === ' '
		if (charIsSpace !== inWhitespace && current) {
			tokens.push(current)
			current = ''
		}
		if (pendingAnsi) { current += pendingAnsi; pendingAnsi = '' }
		inWhitespace = charIsSpace
		current += char
		i++
	}
	if (pendingAnsi) current += pendingAnsi
	if (current) tokens.push(current)
	return tokens
}

function breakLongWord(word: string, width: number, tracker: AnsiCodeTracker): string[] {
	const lines: string[] = []
	let currentLine = tracker.getActiveCodes()
	let currentWidth = 0

	// Collect segments (ANSI codes + grapheme clusters)
	const segments: Array<{ type: 'ansi' | 'grapheme'; value: string }> = []
	let i = 0
	while (i < word.length) {
		const ansiResult = extractAnsiCode(word, i)
		if (ansiResult) {
			segments.push({ type: 'ansi', value: ansiResult.code })
			i += ansiResult.length
		} else {
			let end = i
			while (end < word.length && !extractAnsiCode(word, end)) end++
			for (const seg of segmenter.segment(word.slice(i, end))) {
				segments.push({ type: 'grapheme', value: seg.segment })
			}
			i = end
		}
	}

	for (const seg of segments) {
		if (seg.type === 'ansi') {
			currentLine += seg.value
			tracker.process(seg.value)
			continue
		}
		const w = graphemeWidth(seg.value)
		if (currentWidth + w > width) {
			lines.push(currentLine)
			currentLine = tracker.getActiveCodes()
			currentWidth = 0
		}
		currentLine += seg.value
		currentWidth += w
	}
	if (currentLine) lines.push(currentLine)
	return lines.length > 0 ? lines : ['']
}

function wrapSingleLine(line: string, width: number): string[] {
	if (!line) return ['']
	if (visibleWidth(line) <= width) return [line]

	const wrapped: string[] = []
	const tracker = new AnsiCodeTracker()
	const tokens = splitIntoTokensWithAnsi(line)
	let currentLine = ''
	let currentVisibleLength = 0

	for (const token of tokens) {
		const tokenVisibleLength = visibleWidth(token)
		const isWhitespace = token.trim() === ''

		if (tokenVisibleLength > width && !isWhitespace) {
			if (currentLine) {
				wrapped.push(currentLine)
				currentLine = ''
				currentVisibleLength = 0
			}
			const broken = breakLongWord(token, width, tracker)
			wrapped.push(...broken.slice(0, -1))
			currentLine = broken[broken.length - 1]!
			currentVisibleLength = visibleWidth(currentLine)
			continue
		}

		if (currentVisibleLength + tokenVisibleLength > width && currentVisibleLength > 0) {
			wrapped.push(currentLine.trimEnd())
			currentLine = isWhitespace ? tracker.getActiveCodes() : tracker.getActiveCodes() + token
			currentVisibleLength = isWhitespace ? 0 : tokenVisibleLength
		} else {
			currentLine += token
			currentVisibleLength += tokenVisibleLength
		}
		// Update tracker for ANSI codes in the token
		let j = 0
		while (j < token.length) {
			const ansi = extractAnsiCode(token, j)
			if (ansi) { tracker.process(ansi.code); j += ansi.length; continue }
			j++
		}
	}

	if (currentLine) wrapped.push(currentLine)
	return wrapped.length > 0 ? wrapped.map(l => l.trimEnd()) : ['']
}

export function wrapTextWithAnsi(text: string, width: number): string[] {
	if (!text) return ['']
	const inputLines = text.split('\n')
	const result: string[] = []
	for (const inputLine of inputLines) {
		result.push(...wrapSingleLine(inputLine, width))
	}
	return result.length > 0 ? result : ['']
}

// ---------------------------------------------------------------------------
// Markdown Theme
// ---------------------------------------------------------------------------

export interface MarkdownTheme {
	heading: (text: string) => string
	link: (text: string) => string
	linkUrl: (text: string) => string
	code: (text: string) => string
	codeBlock: (text: string) => string
	codeBlockBorder: (text: string) => string
	quote: (text: string) => string
	quoteBorder: (text: string) => string
	hr: (text: string) => string
	listBullet: (text: string) => string
	bold: (text: string) => string
	italic: (text: string) => string
	strikethrough: (text: string) => string
	underline: (text: string) => string
	/**
	 * Optional syntax highlighting for code blocks.
	 * Receives the raw code and optional language tag.
	 * Returns array of styled lines.
	 * If not provided, codeBlock style is used for every line.
	 */
	highlightCode?: (code: string, lang?: string) => string[]
	/** Prefix applied to each rendered code block line (default: "  ") */
	codeBlockIndent?: string
}

export interface DefaultTextStyle {
	color?: (text: string) => string
	bold?: boolean
	italic?: boolean
	strikethrough?: boolean
	underline?: boolean
}

// ---------------------------------------------------------------------------
// Default theme – basic ANSI colors (no chalk dependency)
// ---------------------------------------------------------------------------

const RESET = '\x1b[0m'

function ansi(code: number | string) {
	return (text: string) => `\x1b[${code}m${text}${RESET}`
}

export const DEFAULT_THEME: MarkdownTheme = {
	heading: ansi('1;34'),       // bold blue
	link: ansi('4;34'),          // underline blue
	linkUrl: ansi('2'),           // dim
	code: ansi('33'),             // yellow
	codeBlock: ansi('32'),        // green
	codeBlockBorder: ansi('2'),   // dim
	quote: ansi('3;2'),           // italic dim
	quoteBorder: ansi('2'),       // dim
	hr: ansi('2'),                // dim
	listBullet: ansi('36'),       // cyan
	bold: ansi('1'),
	italic: ansi('3'),
	strikethrough: ansi('9'),
	underline: ansi('4'),
	highlightCode: lazyHighlightCode,
}

// ---------------------------------------------------------------------------
// Strict strikethrough tokenizer (~~text~~ only, ~text~ kept as literal)
// ---------------------------------------------------------------------------

const STRICT_STRIKETHROUGH_REGEX = /^(~~)(?=[^\s~])((?:\\.|[^\\])*?(?:\\.|[^\s~\\]))\1(?=[^~]|$)/
class StrictStrikethroughTokenizer extends Tokenizer {
	override del(src: string): Tokens.Del | undefined {
		const match = STRICT_STRIKETHROUGH_REGEX.exec(src)
		if (!match) return undefined
		return {
			type: 'del',
			raw: match[0],
			text: match[2]!,
			tokens: this.lexer.inlineTokens(match[2]!),
		}
	}
}

const markdownParser = new Marked()
markdownParser.setOptions({ tokenizer: new StrictStrikethroughTokenizer() })

// ---------------------------------------------------------------------------
// Syntax highlighting (cli-highlight -> ANSI)
// ---------------------------------------------------------------------------

/**
 * Build a cli-highlight theme using raw ANSI escape codes.
 * Maps common token types to simple 16-color ANSI styles.
 */
function buildCliHighlightTheme(): CliHighlightTheme {
	const RESET = '\x1b[0m'
	const wrap = (code: string) => (s: string) => `\x1b[${code}m${s}${RESET}`

	return {
		keyword: wrap('35'),        // magenta
		built_in: wrap('36'),       // cyan
		type: wrap('36;1'),         // bold cyan
		literal: wrap('33'),        // yellow
		number: wrap('33'),         // yellow
		string: wrap('32'),         // green
		comment: wrap('2'),         // dim
		function: wrap('33'),       // yellow
		title: wrap('33'),          // yellow (function/class declarations)
		class: wrap('36;1'),        // bold cyan
		attr: wrap('36'),           // cyan
		variable: wrap('37'),       // white
		params: wrap('2'),          // dim
		regexp: wrap('31'),         // red
		subst: wrap('35'),          // magenta
		meta: wrap('2'),            // dim
		tag: wrap('35'),            // magenta
		name: wrap('35'),           // magenta
		addition: wrap('32'),       // green
		deletion: wrap('31'),       // red
		default: (s: string) => s,
	}
}

const cliHighlightTheme = buildCliHighlightTheme()

/**
 * Syntax highlight code using cli-highlight, outputting ANSI-styled lines.
 * Falls back to plain styling if the language is not supported.
 */
function lazyHighlightCode(code: string, lang?: string): string[] {
	// Validate language before highlighting (avoids stderr spam from cli-highlight).
	// Skip highlighting when no valid language is specified – auto-detection is
	// unreliable and can misidentify prose as code.
	const validLang = lang && supportsLanguage(lang) ? lang : undefined
	if (!validLang) {
		return code.split('\n').map(line => ansi('32')(line))
	}

	try {
		return highlight(code, {
			language: validLang,
			ignoreIllegals: true,
			theme: cliHighlightTheme,
		}).split('\n')
	} catch {
		return code.split('\n').map(line => ansi('32')(line))
	}
}

// ---------------------------------------------------------------------------
// Main render function
// ---------------------------------------------------------------------------

export function renderMarkdown(
	text: string,
	width: number,
	theme: MarkdownTheme = DEFAULT_THEME,
	defaultStyle?: DefaultTextStyle,
): string[] {
	if (!text || text.trim() === '') return []

	const tokens = markdownParser.lexer(text.replace(/\t/g, '   '))
	const renderedLines: string[] = []

	for (let i = 0; i < tokens.length; i++) {
		const token = tokens[i]!
		const nextToken = tokens[i + 1]
		renderedLines.push(...renderToken(token, width, nextToken?.type, theme, defaultStyle))
	}

	// Wrap lines (ANSI-aware)
	const wrappedLines: string[] = []
	for (const line of renderedLines) {
		wrappedLines.push(...wrapTextWithAnsi(line, width))
	}

	return wrappedLines
}

// ---------------------------------------------------------------------------
// Token rendering
// ---------------------------------------------------------------------------

interface InlineStyleContext {
	applyText: (text: string) => string
	stylePrefix: string
}

function getStylePrefix(styleFn: (text: string) => string): string {
	const sentinel = '\u0000'
	const styled = styleFn(sentinel)
	const idx = styled.indexOf(sentinel)
	return idx >= 0 ? styled.slice(0, idx) : ''
}

function getDefaultStyleContext(defaultStyle?: DefaultTextStyle): InlineStyleContext {
	if (!defaultStyle) {
		return { applyText: (t: string) => t, stylePrefix: '' }
	}
	const sentinel = '\u0000'
	let styled = sentinel
	if (defaultStyle.color) styled = defaultStyle.color(styled)
	const idx = styled.indexOf(sentinel)
	const prefix = idx >= 0 ? styled.slice(0, idx) : ''
	return {
		applyText: (text: string) => {
			let s = text
			if (defaultStyle.color) s = defaultStyle.color(s)
			return s
		},
		stylePrefix: prefix,
	}
}

function renderToken(
	token: Token,
	width: number,
	nextTokenType: string | undefined,
	theme: MarkdownTheme,
	defaultStyle?: DefaultTextStyle,
): string[] {
	const lines: string[] = []
	const styleContext = getDefaultStyleContext(defaultStyle)

	switch (token.type) {
		case 'heading': {
			const level = token.depth
			const prefix = '#'.repeat(level) + ' '
			let headingFn: (text: string) => string
			if (level === 1) {
				headingFn = (t: string) => theme.heading(theme.bold(theme.underline(t)))
			} else {
				headingFn = (t: string) => theme.heading(theme.bold(t))
			}
			const headingCtx: InlineStyleContext = {
				applyText: headingFn,
				stylePrefix: getStylePrefix(headingFn),
			}
			const headingText = renderInlineTokens(token.tokens || [], headingCtx, theme)
			const styledHeading = level >= 3 ? headingFn(prefix) + headingText : headingText
			lines.push(styledHeading)
			if (nextTokenType && nextTokenType !== 'space') lines.push('')
			break
		}

		case 'paragraph': {
			const text = renderInlineTokens(token.tokens || [], styleContext, theme)
			lines.push(text)
			if (nextTokenType && nextTokenType !== 'list' && nextTokenType !== 'space') lines.push('')
			break
		}

		case 'code': {
			const indent = theme.codeBlockIndent ?? '  '
			lines.push(theme.codeBlockBorder('```' + (token.lang || '')))
			if (theme.highlightCode) {
				for (const hlLine of theme.highlightCode(token.text, token.lang)) {
					lines.push(indent + hlLine)
				}
			} else {
				for (const codeLine of token.text.split('\n')) {
					lines.push(indent + theme.codeBlock(codeLine))
				}
			}
			lines.push(theme.codeBlockBorder('```'))
			if (nextTokenType && nextTokenType !== 'space') lines.push('')
			break
		}

		case 'list': {
			lines.push(...renderList(token as any, 0, theme, styleContext))
			break
		}

		case 'table': {
			lines.push(...renderTable(token as any, width, nextTokenType, theme, styleContext))
			break
		}

		case 'blockquote': {
			const quoteStyle = (t: string) => theme.quote(theme.italic(t))
			const quotePrefix = getStylePrefix(quoteStyle)
			const quoteCtx: InlineStyleContext = { applyText: (t: string) => t, stylePrefix: quotePrefix }

			const quoteContentWidth = Math.max(1, width - 2)
			const quoteTokens = token.tokens || []
			const quoteLines: string[] = []
			for (let i = 0; i < quoteTokens.length; i++) {
				quoteLines.push(...renderToken(quoteTokens[i]!, quoteContentWidth, quoteTokens[i + 1]?.type, theme, undefined))
			}
			// Remove trailing blank line
			while (quoteLines.length > 0 && quoteLines[quoteLines.length - 1] === '') quoteLines.pop()
			for (const ql of quoteLines) {
				const reapply = ql.replace(/\x1b\[0m/g, '\x1b[0m' + quotePrefix)
				const styled = quoteStyle(reapply)
				const wrapped = wrapTextWithAnsi(styled, quoteContentWidth)
				for (const w of wrapped) lines.push(theme.quoteBorder('│ ') + w)
			}
			if (nextTokenType && nextTokenType !== 'space') lines.push('')
			break
		}

		case 'hr':
			lines.push(theme.hr('─'.repeat(Math.min(width, 80))))
			if (nextTokenType && nextTokenType !== 'space') lines.push('')
			break

		case 'html':
			if ('raw' in token && typeof token.raw === 'string') {
				lines.push(styleContext.applyText(token.raw.trim()))
			}
			break

		case 'space':
			lines.push('')
			break

		default:
			if ('text' in token && typeof token.text === 'string') {
				lines.push(token.text)
			}
	}

	return lines
}

function renderInlineTokens(
	tokens: Token[],
	styleContext: InlineStyleContext,
	theme: MarkdownTheme,
): string {
	let result = ''
	const { applyText, stylePrefix } = styleContext

	for (const token of tokens) {
		switch (token.type) {
			case 'text':
				if (token.tokens && token.tokens.length > 0) {
					result += renderInlineTokens(token.tokens, styleContext, theme)
				} else {
					result += applyText(token.text)
				}
				break

			case 'paragraph':
				result += renderInlineTokens(token.tokens || [], styleContext, theme)
				break

			case 'strong': {
				const content = renderInlineTokens(token.tokens || [], styleContext, theme)
				result += theme.bold(content) + stylePrefix
				break
			}

			case 'em': {
				const content = renderInlineTokens(token.tokens || [], styleContext, theme)
				result += theme.italic(content) + stylePrefix
				break
			}

			case 'codespan':
				result += theme.code(token.text) + stylePrefix
				break

			case 'link': {
				const linkText = renderInlineTokens(token.tokens || [], styleContext, theme)
				const styledLink = theme.link(theme.underline(linkText))
				// Check if link text matches href (bare URLs / autolinked emails)
				const hrefForComparison = token.href.startsWith('mailto:') ? token.href.slice(7) : token.href
				if (token.text === token.href || token.text === hrefForComparison) {
					result += styledLink + stylePrefix
				} else {
					result += styledLink + theme.linkUrl(' (' + token.href + ')') + stylePrefix
				}
				break
			}

			case 'br':
				result += '\n'
				break

			case 'del': {
				const content = renderInlineTokens(token.tokens || [], styleContext, theme)
				result += theme.strikethrough(content) + stylePrefix
				break
			}

			case 'html':
				if ('raw' in token && typeof token.raw === 'string') {
					result += applyText(token.raw)
				}
				break

			default:
				if ('text' in token && typeof token.text === 'string') {
					result += applyText(token.text)
				}
		}
	}

	// Trim trailing stylePrefix
	while (stylePrefix && result.endsWith(stylePrefix)) {
		result = result.slice(0, -stylePrefix.length)
	}
	return result
}

// ---------------------------------------------------------------------------
// Lists (nested support)
// ---------------------------------------------------------------------------

function renderList(
	token: Token & { items: any[]; ordered: boolean; start?: number },
	depth: number,
	theme: MarkdownTheme,
	styleContext: InlineStyleContext,
): string[] {
	const lines: string[] = []
	const indent = '  '.repeat(depth)
	const startNumber = token.start ?? 1

	for (let i = 0; i < token.items.length; i++) {
		const item = token.items[i]
		const bullet = token.ordered ? `${startNumber + i}. ` : '- '

		const itemLines = renderListItem(item.tokens || [], depth, theme, styleContext)
		if (itemLines.length > 0) {
			const firstLine = itemLines[0]!
			const isNestedList = /^\s+\x1b\[36m[-\d]/.test(firstLine)
			if (isNestedList) {
				lines.push(firstLine)
			} else {
				lines.push(indent + theme.listBullet(bullet) + firstLine)
			}
			for (let j = 1; j < itemLines.length; j++) {
				const line = itemLines[j]!
				const isNestedListLine = /^\s+\x1b\[36m[-\d]/.test(line)
				if (isNestedListLine) {
					lines.push(line)
				} else {
					lines.push(`${indent}  ${line}`)
				}
			}
		} else {
			lines.push(indent + theme.listBullet(bullet))
		}
	}
	return lines
}

function renderListItem(
	tokens: Token[],
	parentDepth: number,
	theme: MarkdownTheme,
	styleContext: InlineStyleContext,
): string[] {
	const lines: string[] = []
	for (const token of tokens) {
		if (token.type === 'list') {
			lines.push(...renderList(token as any, parentDepth + 1, theme, styleContext))
		} else if (token.type === 'text') {
			const text = token.tokens && token.tokens.length > 0
				? renderInlineTokens(token.tokens, styleContext, theme)
				: token.text || ''
			lines.push(text)
		} else if (token.type === 'paragraph') {
			lines.push(renderInlineTokens(token.tokens || [], styleContext, theme))
		} else if (token.type === 'code') {
			const indent = theme.codeBlockIndent ?? '  '
			lines.push(theme.codeBlockBorder('```' + (token.lang || '')))
			if (theme.highlightCode) {
				for (const hlLine of theme.highlightCode(token.text, token.lang)) lines.push(indent + hlLine)
			} else {
				for (const codeLine of token.text.split('\n')) lines.push(indent + theme.codeBlock(codeLine))
			}
			lines.push(theme.codeBlockBorder('```'))
		} else {
			const text = renderInlineTokens([token], styleContext, theme)
			if (text) lines.push(text)
		}
	}
	return lines
}

// ---------------------------------------------------------------------------
// Tables (width-aware, column wrapping)
// ---------------------------------------------------------------------------

function renderTable(
	token: Token & { header: any[]; rows: any[][]; raw?: string },
	availableWidth: number,
	nextTokenType: string | undefined,
	theme: MarkdownTheme,
	styleContext: InlineStyleContext,
): string[] {
	const lines: string[] = []
	const numCols = token.header.length
	if (numCols === 0) return lines

	// Border overhead: "│ " + (n-1)*" │ " + " │" = 3n + 1
	const borderOverhead = 3 * numCols + 1
	const availableForCells = availableWidth - borderOverhead
	if (availableForCells < numCols) {
		const fallback = token.raw ? wrapTextWithAnsi(token.raw, availableWidth) : []
		if (nextTokenType && nextTokenType !== 'space') fallback.push('')
		return fallback
	}

	// Natural column widths
	const naturalWidths: number[] = new Array(numCols).fill(0)
	for (let i = 0; i < numCols; i++) {
		const h = renderInlineTokens(token.header[i].tokens || [], styleContext, theme)
		naturalWidths[i] = Math.max(naturalWidths[i]!, visibleWidth(h))
	}
	for (const row of token.rows) {
		for (let i = 0; i < row.length && i < numCols; i++) {
			const c = renderInlineTokens(row[i].tokens || [], styleContext, theme)
			naturalWidths[i] = Math.max(naturalWidths[i]!, visibleWidth(c))
		}
	}

	const totalNatural = naturalWidths.reduce((a, b) => a + b, 0)
	const columnWidths: number[] =
		totalNatural <= availableForCells
			? naturalWidths.slice()
			: shrinkColumns(naturalWidths, availableForCells)

	// Render
	const border = (cells: number[], l: string, m: string, r: string) =>
		l + cells.map(w => '─'.repeat(w)).join(m) + r

	lines.push(border(columnWidths, '┌─', '─┬─', '─┐'))

	// Header
	const headerCellLines = token.header.map((cell, i) =>
		wrapCellText(renderInlineTokens(cell.tokens || [], styleContext, theme), columnWidths[i]!))
	const headerLineCount = Math.max(...headerCellLines.map(c => c.length))
	for (let li = 0; li < headerLineCount; li++) {
		const parts = headerCellLines.map((cl, ci) => {
			const t = cl[li] || ''
			return theme.bold(t + ' '.repeat(Math.max(0, columnWidths[ci]! - visibleWidth(t))))
		})
		lines.push('│ ' + parts.join(' │ ') + ' │')
	}

	lines.push(border(columnWidths, '├─', '─┼─', '─┤'))

	// Rows
	for (let ri = 0; ri < token.rows.length; ri++) {
		const row = token.rows[ri]!
		const rowCellLines = row.map((cell, ci) =>
			wrapCellText(renderInlineTokens(cell.tokens || [], styleContext, theme), columnWidths[ci]!))
		const rowLineCount = Math.max(...rowCellLines.map(c => c.length))
		for (let li = 0; li < rowLineCount; li++) {
			const parts = rowCellLines.map((cl, ci) => {
				const t = cl[li] || ''
				return t + ' '.repeat(Math.max(0, columnWidths[ci]! - visibleWidth(t)))
			})
			lines.push('│ ' + parts.join(' │ ') + ' │')
		}
		if (ri < token.rows.length - 1) {
			lines.push(border(columnWidths, '├─', '─┼─', '─┤'))
		}
	}

	lines.push(border(columnWidths, '└─', '─┴─', '─┘'))
	if (nextTokenType && nextTokenType !== 'space') lines.push('')
	return lines
}

function wrapCellText(text: string, maxWidth: number): string[] {
	return wrapTextWithAnsi(text, Math.max(1, maxWidth))
}

function shrinkColumns(naturalWidths: number[], availableWidth: number): number[] {
	const n = naturalWidths.length
	let widths = naturalWidths.map(w => Math.max(1, w))
	let total = widths.reduce((a, b) => a + b, 0)
	while (total > availableWidth) {
		// Find the widest column and shrink it by 1
		let maxIdx = 0
		for (let i = 1; i < n; i++) {
			if (widths[i]! > widths[maxIdx]!) maxIdx = i
		}
		if (widths[maxIdx]! <= 1) break
		widths[maxIdx]!--
		total--
	}
	return widths
}
