// Disclaimer: this file was generated by AI.
/**
 * Stream markdown chunks to stdout with progressive rendering.
 * Accumulates text and re-renders on each chunk, overwriting previous output
 * using ANSI cursor movement.
 */

import { renderMarkdown, type MarkdownTheme } from './markdown-ansi.js'

export interface RenderMarkdownStreamOptions {
	/** Markdown theme for styling (uses DEFAULT_THEME if not provided) */
	theme?: MarkdownTheme
	/** Terminal width (default: process.stdout.columns or 80) */
	width?: number
}

export async function renderMarkdownStream(
	stream: AsyncIterable<string>,
	options: RenderMarkdownStreamOptions = {},
): Promise<void> {
	const width = options.width ?? process.stdout.columns ?? 80
	let buffer = ''
	let previousLineCount = 0

	for await (const chunk of stream) {
		buffer += chunk
		const lines = renderMarkdown(buffer, width, options.theme)

		// Clear previous output by moving cursor up and clearing below
		if (previousLineCount > 0) {
			// Move cursor up to the start of previous output
			process.stdout.write(`\x1b[${previousLineCount}A`)
			// Clear from cursor to end of screen
			process.stdout.write('\x1b[J')
		}

		// Write new output
		for (const line of lines) {
			process.stdout.write(line + '\n')
		}

		previousLineCount = lines.length
	}

	// Final trailing newline for clean exit
	process.stdout.write('\n')
}
