// Disclaimer: this file was generated by AI.
/**
 * Stream markdown chunks to stdout with progressive rendering.
 * The stream is split into a committed prefix and a live tail. The committed
 * prefix only advances at stable markdown block boundaries; only the live tail
 * is rewritten. This keeps scrollback mostly append-only while still allowing
 * incomplete multi-line constructs such as code fences, tables, links, and
 * emphasis to settle into their final markdown rendering.
 */

import { renderMarkdown, type MarkdownTheme } from './markdown-ansi.js'

export interface RenderMarkdownStreamOptions {
	/** Markdown theme for styling (uses DEFAULT_THEME if not provided) */
	theme?: MarkdownTheme
	/** Terminal width (default: process.stdout.columns or 80) */
	width?: number
}

function findStablePrefixLength(text: string): number {
	let stablePrefixLength = 0
	let offset = 0
	let fence: { char: '`' | '~'; length: number } | undefined

	while (offset < text.length) {
		const newlineIndex = text.indexOf('\n', offset)
		const hasNewline = newlineIndex !== -1
		const lineEnd = hasNewline ? newlineIndex : text.length
		const rawLine = text.slice(offset, lineEnd)

		if (fence) {
			const closeMatch = rawLine.match(/^ {0,3}(`{3,}|~{3,})/)
			if (
				closeMatch?.[1]?.[0] === fence.char &&
				closeMatch[1].length >= fence.length
			) {
				fence = undefined
				if (hasNewline) stablePrefixLength = lineEnd + 1
			}
		} else {
			const openMatch = rawLine.match(/^ {0,3}(`{3,}|~{3,})/)
			if (openMatch?.[1]) {
				fence = {
					char: openMatch[1][0] as '`' | '~',
					length: openMatch[1].length,
				}
			} else if (hasNewline && rawLine.trim() === '') {
				stablePrefixLength = lineEnd + 1
			}
		}

		if (!hasNewline) break
		offset = lineEnd + 1
	}

	return stablePrefixLength
}

export async function renderMarkdownStream(
	stream: AsyncIterable<string>,
	options: RenderMarkdownStreamOptions = {},
): Promise<void> {
	const width = options.width ?? process.stdout.columns ?? 80
	let buffer = ''
	let committedLineCount = 0
	let liveLineCount = 0
	let outputLineCount = 0
	let needsLeadingNewline = false

	function clearTrailingLines(count: number): void {
		if (count <= 0) return
		process.stdout.write('\r\x1b[K')
		for (let i = 1; i < count; i++) {
			process.stdout.write('\x1b[1A\r\x1b[K')
		}
		outputLineCount -= count
		needsLeadingNewline = false
	}

	function writeLines(lines: string[]): void {
		if (lines.length === 0) return
		if (needsLeadingNewline) process.stdout.write('\n')
		for (let i = 0; i < lines.length; i++) {
			if (i > 0) process.stdout.write('\n')
			process.stdout.write(lines[i]!)
		}
		outputLineCount += lines.length
		needsLeadingNewline = true
	}

	function replaceLiveTail(committedLines: string[], liveLines: string[]): void {
		const replacementLines = [...committedLines, ...liveLines]
		clearTrailingLines(liveLineCount)
		writeLines(replacementLines)
		liveLineCount = liveLines.length
		committedLineCount += committedLines.length
	}

	for await (const chunk of stream) {
		buffer += chunk
		const nextCommittedLength = findStablePrefixLength(buffer)
		const fullLines = renderMarkdown(buffer, width, options.theme)
		const committedPrefixLines = renderMarkdown(buffer.slice(0, nextCommittedLength), width, options.theme)
		const committedLines = committedPrefixLines.slice(committedLineCount)
		const liveLines = fullLines.slice(committedPrefixLines.length)

		replaceLiveTail(committedLines, liveLines)
	}

	const finalLines = renderMarkdown(buffer, width, options.theme)
	const maxSafeRefreshLines = Math.max(0, (process.stdout.rows ?? 24) - 2)
	if (
		outputLineCount > 0 &&
		finalLines.length > 0 &&
		finalLines.length <= maxSafeRefreshLines &&
		outputLineCount <= maxSafeRefreshLines
	) {
		clearTrailingLines(outputLineCount)
		liveLineCount = 0
		writeLines(finalLines)
	}

	if (outputLineCount > 0) process.stdout.write('\n')
}
